import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/notification_models.dart';

// Notifications are generated by Firebase Cloud Messaging (FCM) in production.
// This provider manages the in-app notification list received via FCM payloads.
// For now it starts empty; real notifications are appended by the FCM handler.

final notificationsProvider =
    NotifierProvider<NotificationsNotifier, List<AppNotification>>(
      NotificationsNotifier.new,
    );

final unreadCountProvider = Provider<int>((ref) {
  return ref.watch(notificationsProvider).where((n) => !n.isRead).length;
});

class NotificationsNotifier extends Notifier<List<AppNotification>> {
  @override
  List<AppNotification> build() => const [];

  void add(AppNotification notification) => state = [notification, ...state];

  void markRead(String id) {
    state = [
      for (final n in state)
        if (n.id == id) n.copyWith(isRead: true) else n,
    ];
  }

  void markAllRead() {
    state = [for (final n in state) n.copyWith(isRead: true)];
  }
}
